### ISSUE TITLE
Ciao da Italy

### ISSUE THREAD

**Issue by Claudioappassionato** [Toy-97/Chat-WebUI#1]
Sure! Here’s the translation:

Hello, I tested your project, and I like it a lot. I noticed something curious… I’m using the model through LMSTUDIO, and I observed that if I have it perform an internet search, it provides a good text response, but in the server CMD, the text is much longer and more complete. So I believe that the responses are heavily filtered. Have you noticed this too?

**Comment by Toy-97** [comment]
Hello, I don't have LM Studio installed but the most likely thing is you have custom parameter (temperature, top_p, system prompt etc) running differently in your LM Studio or backend server. Perhaps you can go to Chat WebUI additional setttings and set the Model Parameter to custom and let the text be empty then try again.
